title: "Elnur Khalmetov Portfolio"
description: "Robotics & Engineering Projects"
remote_theme: "mmistakes/minimal-mistakes@4.20"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/#projects"
  - title: "CV"
    url: "/cv/"
